version: "3.1"

services:
  montage-twitter-service:
    ports:
      - "8080:8080"
    build:
      context: ./docker/montage-twitter-service
    volumes:
      - ./:/home/montage-twitter-service/public/:ro
